---
- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install the IUS Community RPM 
  yum: 
    name: http://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm
    state: present

- name: Install PHP 7 packages 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - php70u
  - php70u-pdo
  - php70u-mysqlnd
  - php70u-opcache
  - php70u-xml
  - php70u-mcrypt
  - php70u-gd
  - php70u-devel
  - php70u-mysqlnd
  - php70u-intl
  - php70u-mbstring
  - php70u-bcmath
  - php70u-json
  - php70u-iconv

- name: Clearn yum cache
  command: yum clean all

- name: Install Symfony
  get_url:
    url: https://symfony.com/installer
    dest: /usr/bin/symfony
    owner: root
    group: root
    mode: 0755

- name: Get the PHP composer intaller
  get_url:
    url: https://getcomposer.org/installer
    dest: /composer-setup.php
    checksum: "sha384:e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae"

- name: Install composer
  command: php /composer-setup.php php --install-dir=/usr/bin --filename=composer

- name: Update composer
  command: composer update

- name: Create symfony user
  user:
    name: symfony
    uid: 1000
    group: root
    createhome: no
   
# - name: Remove composer-setup.php
#  file:
#    path: /composer-setup.php
#    state: absent

